name: Release

on: 
  release:
    types: [published]

jobs:
  publish-kusama:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: mangatasolutions/mangata-node
          tags: |
            type=semver,prefix=kusama-,pattern={{version}}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Pull images
        run: |
          docker pull mangatasolutions/mangata-node:kusama-latest
      -
        name: Tag and push images
        run: |
          echo "START"
          echo ${{ steps.meta.outputs.tags }}
          echo "TOP"

  # publish-rococo:
  #
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v2
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     -
  #       name: Docker meta
  #       id: meta
  #       uses: docker/metadata-action@v3
  #       with:
  #         images: mangatasolutions/mangata-node
  #         tags: |
  #           type=semver,prefix=rococo-,pattern={{version}}
  #     -
  #       name: Login to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Pull images
  #       run: |
  #         docker pull mangatasolutions/mangata-node:rococo-${{ github.sha }}
  #     -
  #       name: Tag and push images
  #       run: |
  #         docker tag mangatasolutions/mangata-node:rococo-${{ github.sha }} ${{ steps.meta.outputs.tags }}
  #         docker push mangatasolutions/mangata-node:rococo-${{ steps.meta.outputs.tags }}
